### PR TITLE
Add various methods

### PR DESCRIPTION
**Pull request by hideakitai**
@wssmith @Kyrandian Great work! Can I merge these changes? If you have any concerns, I can merge it manually though.

### CODE REVIEW

**Comment by wssmith** [comment]
I'm happy to hear you're interested in merging the changes but I do have some concerns, mainly that my fork isn't compatible with C++11 as it currently exists. Until now I've been adding traits for personal use, so I didn't worry about maintaining backward compatibility for existing users. Also, if I'd expected you to take interest I wouldn't have made so many cosmetic modifications.

Before merging, I'd like to add preprocessor directives to hide traits using C++14 and C++17 language features when they aren't available. For instance, the shorthand value traits with a _v suffix require support for variable templates and inline variables. I should also remove some recent features I used for stylistic reasons, like the nested namespace syntax "namespace arx::stdx { ... }".

I've been testing these with Arduino AVR boards only, since the SAMD boards I use already have modern standard library support in the toolchain. Arduino currently ships with AVR-GCC 7.3.0, which has partial C++17 language support when enabled with a compiler flag. Most people probably don't bother, but I find the new features useful. Deduction guides seem to be unsupported, but fortunately the only trait I added that uses one is the C++17 implementation of std::reference_wrapper. (I need to replace std::reference_wrapper with a C++11 version before merging anyway-- otherwise there will be multiple definitions when libstdc++11 is present.)

I should also mention that std::is_class, std::is_scalar and std::is_object don't fully conform because they need std::is_union or std::is_enum, which need compiler-specific implementations. I assume this isn't a problem.

Let me know if you have comments or suggestions about any of this. In the meantime, I'll start making the changes I mentioned to facilitate a merge.

**Comment by hideakitai** [comment]
@wssmith Thank you for the reply!

> I'd like to add preprocessor directives to hide traits using C++14 and C++17 language features when they aren't available. 

Cool

> I should also remove some recent features I used for stylistic reasons

OK, it's better for me. Sorry but thanks!

> I've been testing these with Arduino AVR boards only

I think it's enough, too

> I need to replace std::reference_wrapper with a C++11 version before merging

Great

> I should also mention that std::is_class, std::is_scalar and std::is_object don't fully conform because they need std::is_union or std::is_enum, which need compiler-specific implementations

No problem I think

Thank you for your contribution! I'm looking forward to merging.

**Comment by wssmith** [comment]
@hideakitai This is fine to merge now if you're still interested.

**Review by hideakitai — COMMENTED** [review]
I'm sorry for not getting back to you sooner. Thank you so much!

**Pull request merged**
